apiVersion: v2
name: open-zaak
description: Productiewaardige API's voor Zaakgericht Werken

type: application
version: 0.8.1
appVersion: "1.7.1"

dependencies:
  - name: postgresql
    version: ~10.12.0
    repository: https://charts.bitnami.com/bitnami
    tags:
      - postgresql
  - name: redis
    version: ~13.0.0
    repository: https://charts.bitnami.com/bitnami
    tags:
      - redis
