apiVersion: v2
name: open-notificaties
description: API voor het routeren van notificaties

type: application
version: 0.6.0
appVersion: "1.3.0"

dependencies:
  - name: postgresql
    version: ~10.12.0
    repository: https://charts.bitnami.com/bitnami
    tags:
      - postgresql
  - name: redis
    version: ~13.0.0
    repository: https://charts.bitnami.com/bitnami
    tags:
      - redis
  - name: rabbitmq
    version: ~8.23.0
    repository: https://charts.bitnami.com/bitnami
    tags:
      - rabbitmq
